# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    app.storage_engines: '%storage_engines%'
    app.watchers: '%watchers%'

imports:
    - { resource: storage.yaml }
    - { resource: watchers.yaml }

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully qualified class name
    App\:
        resource: '../src/'

    # add more service definitions when explicit configuration is needed,
    # please note that last definitions always *replace* previous ones

    App\Storage\StorageEngineFactory:
        arguments:
            $storageEngineConfigs: '%storage_engines%'

    App\Watcher\WatcherFactory:
        arguments:
            $storageEngineFactory: '@App\Storage\StorageEngineFactory'

    App\Watcher\FileWatcherService: ~
    App\Watcher\Support\MimeMatcher: ~
    App\Watcher\Support\FolderMatcher: ~

    App\Watcher\WatcherKernel:
        arguments:
            $configPath: '%kernel.project_dir%/config/watchers.yaml'

    App\Command\WatchersRunCommand: ~
